'use client';
import {ArrowUp,ArrowDown,Plus,Trash2,RotateCcw} from 'lucide-react';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {initialConfig,receiptText,type Config,type Message} from './templates';
export const presets=[['messages','Just messages'],['conversation','Conversation'],['full','Full phone'],['keyboard','With keyboard'],['receipt','Bill split']] as const;
export function presetConfig(id:string):Config {
 const base:Config={...initialConfig,name:'Alex',avatar:false,thread:false,unread:'3',time:'9:41',dateLabel:'Today 9:41 AM',messages:[{id:'one',direction:'received',text:'How much do we owe you?'},{id:'two',direction:'sent',text:'$17.64 each! Just sent the split.',status:'Read 9:41 AM'}]};
 if(id==='messages')return {...base,header:false,statusBar:false,composer:false,receipt:false};
 if(id==='conversation')return {...base,avatar:true,statusBar:false,showUnread:false};
 if(id==='full')return {...base,avatar:true,timestamp:true,scrollable:true,viewportHeight:844};
 if(id==='keyboard')return {...base,avatar:true,timestamp:true,keyboard:true,scrollable:true,viewportHeight:956};
 if(id==='receipt')return {...base,header:false,statusBar:false,composer:false,thread:true,messages:[{id:'one',direction:'received',text:'How much do we owe you?'},{id:'two',direction:'sent',text:receiptText,width:'246px',status:'Read 12:53 PM'}]};
 return base;
}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="toggle-row"><span>{label}</span><Switch aria-label={label} checked={value} onCheckedChange={onChange}/></div>}
function Choice({label,value,options,onChange}:{label:string;value:string;options:string[][];onChange:(v:string)=>void}){return <label className="field-label">{label}<Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>}
export default function EditorControls({c,onChange,preset,onPreset}:{c:Config;onChange:(v:Config)=>void;preset:string;onPreset:(v:string)=>void}){
 const update=(key:keyof Config,value:unknown)=>onChange({...c,[key]:value});
 const edit=(id:string,patch:Partial<Message>)=>update('messages',c.messages.map(m=>m.id===id?{...m,...patch}:m));
 const toggle=(key:keyof Config,label:string)=><Toggle label={label} value={Boolean(c[key])} onChange={v=>update(key,v)}/>;
 const move=(i:number,delta:number)=>{const next=[...c.messages];[next[i],next[i+delta]]=[next[i+delta],next[i]];update('messages',next)};
 return <aside className="editor rich-editor"><div className="editor-heading"><div><h2>Make it yours</h2><p>Start with a preset. Edit every detail.</p></div><Button variant="ghost" size="icon" aria-label="Reset editor" onClick={()=>onPreset(preset==='custom'?'conversation':preset)}><RotateCcw size={16}/></Button></div>
 <div className="preset-grid rich-presets">{presets.map(([id,label])=><button key={id} className={'preset '+(preset===id?'selected':'')} onClick={()=>onPreset(id)}>{label}</button>)}</div>
 <Accordion type="multiple" defaultValue={['messages']} className="control-sections">
 <AccordionItem value="messages"><AccordionTrigger>Messages <span className="section-count">{c.messages.length}</span></AccordionTrigger><AccordionContent>
 <Accordion type="multiple" defaultValue={['one']} className="stack-sections">{c.messages.map((m,i)=><AccordionItem key={m.id} value={m.id}><AccordionTrigger><span className="stack-label"><span>{i+1}. {m.direction==='sent'?'Sent':'Received'}</span><small>{m.text||'Empty message'}</small></span></AccordionTrigger><AccordionContent><div className="stack-tools"><Button size="icon" variant="ghost" disabled={i===0} aria-label={`Move message ${i+1} up`} onClick={()=>move(i,-1)}><ArrowUp size={14}/></Button><Button size="icon" variant="ghost" disabled={i===c.messages.length-1} aria-label={`Move message ${i+1} down`} onClick={()=>move(i,1)}><ArrowDown size={14}/></Button><Button size="icon" variant="ghost" aria-label={`Delete message ${i+1}`} onClick={()=>update('messages',c.messages.filter(x=>x.id!==m.id))}><Trash2 size={14}/></Button></div>
 <Choice label={`Message ${i+1} direction`} value={m.direction} options={[["received","Received"],["sent","Sent"]]} onChange={v=>edit(m.id,{direction:v as Message['direction']})}/>
 <label className="field-label">Message text<textarea aria-label={`Message ${i+1} text`} rows={m.text.length>120?7:3} value={m.text} onChange={e=>edit(m.id,{text:e.target.value})}/></label>
 <label className="field-label">Date / time above message<input aria-label={`Message ${i+1} timestamp`} placeholder="e.g. Yesterday 8:32 PM" value={m.timestamp||''} onChange={e=>edit(m.id,{timestamp:e.target.value})}/></label>
 <Choice label={`Message ${i+1} receipt`} value={!m.status?'none':m.status.startsWith('Read')?'read':m.status==='Delivered'?'delivered':'custom'} options={[["none","None"],["delivered","Delivered"],["read","Read"],["custom","Custom label"]]} onChange={v=>edit(m.id,{status:v==='none'?'':v==='delivered'?'Delivered':v==='read'?'Read 9:41 AM':'Sent'})}/>
 {!!m.status&&m.status!=='Delivered'&&<label className="field-label">{m.status.startsWith('Read')?'Read time':'Receipt label'}<input aria-label={`Message ${i+1} receipt label`} value={m.status.startsWith('Read')?m.status.replace(/^Read\s?/,''):m.status} onChange={e=>edit(m.id,{status:m.status?.startsWith('Read')?'Read '+e.target.value:e.target.value})}/></label>}
 <label className="field-label">Bubble width (optional)<input aria-label={`Message ${i+1} width`} placeholder="Auto, or e.g. 246px / 70%" value={m.width||''} onChange={e=>edit(m.id,{width:e.target.value})}/></label><Choice label={`Message ${i+1} grouping`} value={m.group||'single'} options={[["single","Standalone"],["first","First in group"],["middle","Middle of group"],["last","Last in group"]]} onChange={v=>edit(m.id,{group:v==='single'?undefined:v as Message['group']})}/><Toggle label={`Message ${i+1} tail`} value={m.tail!==false} onChange={v=>edit(m.id,{tail:v})}/>
 </AccordionContent></AccordionItem>)}</Accordion>
 {c.messages.length===0&&<p className="empty-stack">Your canvas is empty. Add a message to begin.</p>}
 <Button variant="outline" className="stack-add" onClick={()=>update('messages',[...c.messages,{id:crypto.randomUUID(),direction:c.messages.at(-1)?.direction==='sent'?'received':'sent',text:'Your message here'}])}><Plus size={16}/>Add message</Button>
 {toggle('tails','Show bubble tails')}{toggle('receipt','Show receipts')}{toggle('thread','Reply thread')}
 </AccordionContent></AccordionItem>
 <AccordionItem value="header"><AccordionTrigger>Profile & navigation</AccordionTrigger><AccordionContent>{toggle('header','Profile header')}<label className="field-label">Contact name<input value={c.name} onChange={e=>update('name',e.target.value)}/></label>{toggle('avatar','Profile photo')}<label className="field-label">Profile image URL<input type="url" placeholder="Blank uses fictional demo portrait" value={c.avatarUrl} onChange={e=>update('avatarUrl',e.target.value)}/></label>{toggle('back','Back button')}{toggle('showUnread','Show back-button count')}<label className="field-label">Back-button count<input type="number" min="0" value={c.unread} onChange={e=>update('unread',e.target.value)}/></label>{toggle('video','FaceTime button')}</AccordionContent></AccordionItem>
 <AccordionItem value="status"><AccordionTrigger>Status bar & dates</AccordionTrigger><AccordionContent>{toggle('statusBar','Status bar')}{toggle('clock','Show time')}<label className="field-label">Status-bar time<input value={c.time} onChange={e=>update('time',e.target.value)}/></label>{toggle('signal','Cellular signal')}{toggle('wifi','Wi-Fi icon')}{toggle('battery','Battery icon')}{toggle('island','Dynamic Island')}{toggle('timestamp','Conversation date')}<label className="field-label">Conversation date label<input value={c.dateLabel} onChange={e=>update('dateLabel',e.target.value)}/></label></AccordionContent></AccordionItem>
 <AccordionItem value="input"><AccordionTrigger>Composer & keyboard</AccordionTrigger><AccordionContent>{toggle('composer','Message input')}{toggle('plus','Add button')}{toggle('microphone','Microphone')}{toggle('keyboard','Keyboard')}<p className="control-hint">The on-screen keyboard types into the message input. Return adds your message.</p></AccordionContent></AccordionItem>
 <AccordionItem value="canvas"><AccordionTrigger>Canvas & scrolling</AccordionTrigger><AccordionContent>{toggle('scrollable','Scrollable conversation')}<p className="control-hint">{c.scrollable?'Messages scroll inside a fixed canvas. The header and keyboard stay in place.':'The canvas grows to fit every message, ready to reuse as a flat composition.'}</p>{c.scrollable&&<label className="field-label">Canvas height (px)<input type="number" min={c.keyboard?700:240} max="1600" step="20" value={c.viewportHeight} onChange={e=>update('viewportHeight',Math.max(c.keyboard?700:240,Math.min(1600,Number(e.target.value))))}/></label>}</AccordionContent></AccordionItem>
 <AccordionItem value="style"><AccordionTrigger>Colors & typography</AccordionTrigger><AccordionContent><Toggle label="Light appearance" value={c.theme==='light'} onChange={v=>onChange({...c,theme:v?'light':'dark',background:v?'#ffffff':'#000000',received:v?'#e9e9eb':'#262628'})}/>{[['background','Background'],['sent','Sent bubble'],['received','Received bubble']].map(([key,label])=><label className="color-row" key={key}><span>{label}</span><code>{String(c[key as keyof Config])}</code><input type="color" aria-label={label} value={String(c[key as keyof Config])} onChange={e=>update(key as keyof Config,e.target.value)}/></label>)}{([['fontSize','Font size',13,25,'px'],['maxWidth','Maximum bubble width',45,95,'%']] as const).map(([key,label,min,max,unit])=><div className="range-row" key={key}><div>{label}<span>{c[key]}{unit}</span></div><Slider ref={el=>{el?.querySelector('[role="slider"]')?.setAttribute('aria-label',label)}} min={min} max={max} value={[c[key]]} onValueChange={v=>update(key,v[0])}/></div>)}</AccordionContent></AccordionItem>
 </Accordion></aside>
}
